# ClientWorker.js.org
name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://fastly.jsdelivr.net/npm/clientworker
  - https://npm.onmicrosoft.cn/clientworker
# Config热更新
hotconfig:
  - https://fastly.jsdelivr.net/gh/xlenco/blog@main/source/config.yaml
catch_rules:
  # 站点多线路选择
  - rule: _
    transform_rules:
      - search: _ 
        replace: 
          - _
          - xlenco.github.io #GithubPage托管
          - xlenco.pages.dev #Cloudflare托管
         # - xlenco.netlify.app #Netlify托管
        action: fetch
        fetch:
          status: .*
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*2 # 缓存8小时
            delay: 200
