# ClientWorker.js.org
name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://fastly.jsdelivr.net/npm/clientworker
  - https://npm.onmicrosoft.cn/clientworker
# Config热更新
hotconfig:
  - https://fastly.jsdelivr.net/gh/xlenco/blog@main/source/config.yaml
catch_rules:
  # 站点多线路选择
  - rule: _
    transform_rules:
      - search: _ 
        replace: 
          - xlenco.github.io #GithubPage托管
          - xlenco.pages.dev #Cloudflare托管
         # - xlenco.netlify.app #Netlify托管
          - _
        action: fetch
        fetch:
          status: .*
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*2 # 缓存8小时
            delay: 200
# 静态资源 CDN 选择
  - rule: ^https\:\/\/((cdn|test1|quantil)\.jsdelivr\.net\/npm|npm\.elemecdn\.com)
    transform_rules:
      - search: _
        replace:
          - https://unpkg.com
          - https://npm.elemecdn.com 
          - https://npm.sourcegcdn.com 
          - https://cdn.bilicdn.tk/npm 
          - https://cdn.staticfile.org
          - _
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false # false
          timeout: 3000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
  # github加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh)
    transform_rules:
      - search: _
        replace:
          - https://fastly.jsdelivr.net/gh
          - https://gcore.jsdelivr.net/gh
          - https://cdn.bilicdn.tk/gh
          - https://jsd.onmicrosoft.cn/gh
          - _
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*8 # 缓存8小时
            delay: 300
