name: ClientWorker 
catch_rules:
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _ 
        action: fetch
        fetch:
          engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503
  # 不劫持（丢给浏览器）
  - rule: .*
    transform_rules:
      - search: _
        action: skip #? 2.8.1新增，跳过cw规则（ 现在已经不在需要）
