# ClientWorker.js.org
name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://unpkg.onmicrosoft.cn/clientworker
catch_rules:         
# 静态资源 CDN 选择
  - rule: ^https\:\/\/((cdn|test1|quantil|fastly|gcore)\.jsdelivr\.net\/npm|unpkg\.com)
    transform_rules:
      - search: _
        replace:
          - _
          - https://unpkg.onmicrosoft.cn 
          - https://jsd.onmicrosoft.cn/npm
          - https://npm.onmicrosoft.cn
          - https://cdn.cnortles.top/npm
          - https://unpkg.cnortles.top   
          - https://jsd.cky.codes/npm   
          - https://npm.elemecdn.com
          - https://npm.sourcegcdn.com 
          - https://cdn.bilicdn.tk/npm 
          - https://cdn.staticfile.org
          - https://cdn.bilicdn.tk/npm
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false # false
          timeout: 3000
          cache:
            expire: 1000*60*60*12 # 缓存8小时
            delay: 300
  # github加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh)
    transform_rules:
      - search: _
        replace:
          - _
          - https://jsd.onmicrosoft.cn/gh
          - https://cdn.cnortles.top/gh
          - https://fastly.jsdelivr.net/gh
          - https://gcore.jsdelivr.net/gh
          - https://cdn.bilicdn.tk/gh
          - https://jsd.cky.codes/gh
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false # false
          timeout: 30000
          cache:
            expire: 1000*60*60*12 # 缓存8小时
            delay: 300
# 更换不蒜子统计
  - rule: ^https\:\/\/busuanzi\.ibruce\.info\/busuanzi\/2.3\/busuanzi\.pure\.mini\.js
    transform_rules:
      - search: ^https\:\/\/busuanzi\.ibruce\.info\/busuanzi\/2.3\/busuanzi\.pure\.mini\.js
        replace: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
        action: fetch
        fetch:
          engine: fetch
          status: 200
          preflight: false
          timeout: 30000
          delay: 300
  # 第三方api图片缓存
  - rule: ^https\:\/\/xlenco\.onmicrosoft\.cn
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: 200
          engine: fetch
          preflight: false # false
          timeout: 50000
          cache:
            expire: 1000*60*60*24 # 缓存24小时
            delay: 300       
# 匹配B站资源链接
  - rule: ^(http|https)\:\/\/(i0|i1|i2|i3|s1|s2|s3)\.hdslb\.com 
    transform_rules:
      - search: _ # 多cdn并发
        replace:
          - https://s1.hdslb.com
          - https://s2.hdslb.com
          - https://s3.hdslb.com
        action: fetch
        fetch:
          engine: parallel
          status: 200
          preflight: false
          timeout: 30000
          delay: 4000
