# ClientWorker.js.org
name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://jsd.onmicrosoft.cn/npm/clientworker@latest
# Config热更新
hotconfig:
  - https://jsd.onmicrosoft.cn/gh/xlenco/blog@main/source/config.yaml
catch_rules:
  # 站点多线路选择
  - rule: _
    transform_rules:
      - search: _ 
        replace: 
          - _
        #  - xlenco.github.io #GithubPage托管
        # - xlenco.onrender.com #render托管
        # - netlify.xlenco.eu.org #Netlify托管
          - xlenco.pages.dev #Cloudflare托管
        action: fetch
        fetch:
          status: .*
          engine: parallel
          preflight: false
          timeout: 3000
          cache:
            expire: 1000*60*60*2 # 缓存8小时
            delay: 200
# 静态资源 CDN 选择
  - rule: ^https\:\/\/((cdn|test1|quantil|fastly|gcore)\.jsdelivr\.net\/npm|npm\.elemecdn\.com)
    transform_rules:
      - search: _
        replace:
          - _
          - https://jsd.onmicrosoft.cn/npm
          - https://npm.onmicrosoft.cn
          - https://cdn.cbd.int
          - https://jsd.cky.codes/npm
          - https://unpkg.com
          - https://npm.elemecdn.com
          - https://npm.sourcegcdn.com 
          - https://cdn.bilicdn.tk/npm 
          - https://cdn.staticfile.org
          - https://unpkg.zhimg.com
          - https://cdn.bilicdn.tk/npm
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false
          timeout: 5000
          cache:
            expire: 1000*60*60*8
            delay: 3000
  # github加速
  - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh)
    transform_rules:
      - search: _
        replace:
          - _
          - https://jsd.onmicrosoft.cn/gh
          - https://jsd.cky.codes/gh
          - https://cdn.cnortles.top/gh
          - https://fastly.jsdelivr.net/gh
          - https://gcore.jsdelivr.net/gh
          - https://cdn.bilicdn.tk/gh
        action: fetch
        fetch:
          status: 200
          engine: parallel
          preflight: false # false
          timeout: 50000
          cache:
            expire: 1000*60*60*8 缓存8小时
            delay: 3000
  # 第三方api图片缓存
  - rule: ^https\:\/\/xlenco\.onmicrosoft\.cn
    transform_rules:
      - search: _
        action: fetch
        fetch:
          status: 200
          engine: crazy
          preflight: false
          threads: 5
          timeout: 30000
          cache:
            enable: true
            expire: 1000*60*60*24

  # 本地资源缓存
  - rule: _
    transform_rules:
      - search: \.(js|ttf|css) 
        action: fetch
        fetch:
          status: .*
          engine: fetch
          preflight: false # false
          timeout: 50000
          cache:
            enable: true
            expire: 1000*60*60 # 缓存1小时
            delay: 300
