# ClientWorker.js.org
name: ClientWorker 
cleaninterval: 1000*20 # 每20秒检测并清理一次缓存
# ClientWorker热补丁
hotpatch:
  - https://fastly.jsdelivr.net/npm/clientworker
  - https://npm.onmicrosoft.cn/clientworker
# Config热更新
hotconfig:
  - https://fastly.jsdelivr.net/gh/xlenco/blog@main/source/config.yaml
catch_rules:
  - rule: _
    transform_rules:
      - search: \#.+
        searchin: url
        replace: ''
      - search: _ 
        action: fetch
        fetch:
          engine: fetch 
      - search: (^4|^5) 
        searchin: status 
        action: return
        return:
          body: The GateWay is down!This Page is provided by ClientWorker!
          status: 503
